management:
  security:
    enabled: false
eureka:
  instance:
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
    ## 使用ip地址
    preferIpAddress: true
    ## 注册中心的实力名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}/${spring.application.name}/${random.value}
server:
  port: 8090
spring:
  boot:
    admin:
      context-path: /monitor
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
  application:
    name: @project.build.finalName@
security:
  user:
    name: admin
    password: 123456


