server:
  port: 9060
  compression:
    enabled: true
   # mime-types: application/json,application/xml,text/html,text/xml,text/plain
  context-path: /@project.build.finalName@
eureka:
  instance:
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
    ## 使用ip地址
    preferIpAddress: true
    ## 注册中心的实力名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}/${spring.application.name}
    status-page-url-path: /${spring.application.name}${management.context-path}${endpoints.info.path:/info}
    healthCheckUrlPath: /${spring.application.name}${management.context-path}${endpoints.health.path:/health}
    home-page-url-path: /${spring.application.name}${management.context-path}
    metadata-map:
      management:
         context-path: /${spring.application.name}${management.context-path}
management:
  security:
    enabled: false
  context-path: ${server.context-path}-m
security:
  oauth2:
    resource:
      user-info-uri: http://${vitark.gateway.ip}:${vitark.gateway.port}/vitark-gateway/oauth/oauth-service/user
      prefer-token-info: false
      service-id: rws-service
myconfig: ${profile.active}
logging:
  level.com.netflix.discovery.DiscoveryClient: warn
  config: classpath:logback.xml
  level: debug
feign:
  compression:
    request:
      min-request-size: 2048
  hystrix:
    enabled: true
      #mime-types: text/xml,application/xml,application/json
info:
  application:
    name: rws服务
    desc: 提供真实世界研究功能
    version: @project.version@
    buildTime: @build.time@
spring:
  zipkin:
    base-url: http://localhost:8090
    locator:
      discovery:
        enabled: true
  application:
    ## 应用名称
    name: @project.build.finalName@
  datasource:
     driver-class-name:  com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/tcc_account?useUnicode=true&characterEncoding=utf8
     username: root
     password: 123456
hystrix:
  shareSecurityContext: true
  config:
    stream:
      maxConcurrentConnections: 50
  command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            strategy: THREAD
            thread:
              timeoutInMilliseconds: 6000000
mybatis:
  type-aliases-package: com.gennlife.rws.entity
  config-location: classpath:mybatis/mybatis-config.xml
