server:
  port: 9011
  context-path: /${spring.application.name}
eureka:
  instance:
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
    ## 使用ip地址
    preferIpAddress: true
    ## 注册中心的实力名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}/${spring.application.name}
    status-page-url-path: /${spring.application.name}${management.context-path}${endpoints.info.path:/info}
    healthCheckUrlPath: /${spring.application.name}${management.context-path}${endpoints.health.path:/health}
    home-page-url-path: /${spring.application.name}${management.context-path}
    metadata-map:
      management:
        context-path: /${spring.application.name}${management.context-path}
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  devtools:
    livereload:
      port: 35730
  zipkin:
    base-url: http://localhost:8090
  application:
    name: @project.build.finalName@
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
  context-path: /${spring.application.name}-m
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
info:
  application:
    name: 权限管理中心
    desc: 提供集群统一权限管理认证服务
    version: @project.version@
