#服务端口
spring:
  application:
    name: @project.build.finalName@
server:
  port: 9005
  context-path: /${spring.application.name}
eureka:
  instance:
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}/${spring.application.name}
    status-page-url-path: /${spring.application.name}${management.context-path}${endpoints.info.path:/info}
    healthCheckUrlPath: /${spring.application.name}${management.context-path}${endpoints.health.path:/health}
    home-page-url-path: /${spring.application.name}${management.context-path}
    metadata-map:
      configPath: ${server.context-path}
      context-path: /${spring.application.name}${management.context-path}
management:
  security:
    enabled: false
  context-path: /${spring.application.name}-m
endpoints:
  health:
    sensitive: false
    enabled: true
info:
  application:
    name: 配置中心
    desc: 提供集群统一配置管理
    version: @project.version@
