#service name
spring:
  application:
    name: @project.build.finalName@
  cloud:
    config:
      allow-override: false
#服务端口,访问路径
server:
  port: 8762
  servlet:
    context-path: /${spring.application.name}
#eureka 服务中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
