server:
  port: 9031
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  context-path: /${spring.application.name}
eureka:
  instance:
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
    ## 使用ip地址
    preferIpAddress: true
    ## 注册中心的实力名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}/${spring.application.name}
    status-page-url-path: /${spring.application.name}${management.context-path}${endpoints.info.path:/info}
    health-check-url-path: /${spring.application.name}${management.context-path}${endpoints.health.path:/health}
    home-page-url-path: /${spring.application.name}${management.context-path}
    metadata-map:
      management:
        context-path: /${spring.application.name}${management.context-path}
management:
  security:
    enabled: false
  context-path: /${spring.application.name}-m
endpoints:
  health:
    sensitive: false
    enabled: true
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
    #max-per-route-connections: 30
    #max-total-connections: 100
  routes:
    rws-service:
      path: /**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: rws-service
    user-service:
      path: /**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: user-service
    oauth:
      path: /oauth/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: oauth-service
  ignored-patterns: ${management.context-path}/**
  ribbon-isolation-strategy: thread
  #thread-pool:
  #  use-separate-thread-pools: true
security:
  basic:
    enabled: false
  oauth2:
    client:
      ##网关的地址
      access-token-uri: http://${vitark.gateway.ip}:${vitark.gateway.port}/${spring.application.name}/oauth/oauth-service/oauth/token
      user-authorization-uri: http://${vitark.gateway.ip}:${vitark.gateway.port}/oauth/oauth-service/authorize
    resource:
      user-info-uri:  http://${vitark.gateway.ip}:${vitark.gateway.port}/${spring.application.name}/oauth/oauth-service/user
      prefer-token-info: false

##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000

###超时配置###
logging:
  level:
    root: info
spring:
  zipkin:
    base-url: http://localhost:8090
    locator:
      discovery:
        enabled: true
  application:
    name: @project.build.finalName@
info:
  application:
    name: 网关服务
    desc: 提供后端所有服务的转发、请求拦截、安全控制等功能
    version: @project.version@
    buildTime: @build.time@
