server:
  port: 9026
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  context-path: /@project.build.finalName@
eureka:
  instance:
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
    ## 使用ip地址
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}/${spring.application.name}
    status-page-url-path: ${server.context-path}${management.context-path}${endpoints.info.path:/info}
    healthCheckUrlPath: ${server.context-path}${management.context-path}${endpoints.health.path:/health}
    home-page-url-path: ${server.context-path}${management.context-path}
    metadata-map:
      management:
        context-path: /${spring.application.name}${management.context-path}
spring:
  zipkin:
    base-url: http://localhost:8090
    locator:
      discovery:
        enabled: true
  application:
    name: @project.build.finalName@
myconfig: 5555
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9031/vitark-gateway/oauth/oauth-service/user
      prefer-token-info: false
      service-id: resource
#hystrix:
 # metrics:
 #   enabled: true
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
  context-path: /@project.build.finalName@-m
logging:
  level.com.netflix.discovery.DiscoveryClient: warn
info:
  application:
    name: 用户管理中心
    desc: 提供集群用户管理服务
    version: @project.version@
